### ISSUE TITLE
5. reset password

### ISSUE THREAD

**Issue by anton-pytel** [anton-pytel/camp-app#10]
doplnit moznost reset password

**Comment by anton-pytel** [comment]
@MajkaPytlova - nasadil som potvrdzujuci email a aj reset hesla (ten som neskusal), ked sa ti bude dat over prosim :)

**Comment by MajkaPytlova** [comment]
Ahoj :) skúšala som zmenu hesla rodiča a išlo mi to v pohode :) Čiže im sa
najskôr vygeneruje heslo, ktoré si potom môžu zmeniť, tak?

Majka
