### ISSUE TITLE
Tlačidlo "registruj"

### ISSUE THREAD

**Issue by MajkaPytlova** [anton-pytel/camp-app#14]
Ahoj, skúšame to prihlásenie a čo nám hneď z prvej nešlo, bolo keď sme vyplnili len dieťa a stlačili "registruj", bolo treba vypísať ostatné údaje, čo je logické len to tlačidlo nás zmiatlo, preto ak sa dá, tak z môjho pohľadu by sa mohlo tlačidlo "registruj" nahradiť za "ďalej", ktoré by ich posunulo od sekcie dieťa do sekcie rodič a potom do zdravotného stavu a na záver, keď toto všetko vyplnia dať "registruj". Dalo by sa to? Týmto zároveň skúšam, či viem pracovať aj v tomto "svete", svete githubu.

**Comment by anton-pytel** [comment]
@MajkaPytlova suhlas, upravene v ramci tohto [PR](https://github.com/anton-pytel/camp-app/pull/15) - (pull request), nasadene, mozes overit.
