### ISSUE TITLE
používanie súborov cookies

### ISSUE THREAD

**Issue by MajkaPytlova** [anton-pytel/camp-app#16]
Ahoj, Štefan sa na dnešnom stretnutí pýtal na používanie súborov cookies na stránke, vieš mi k tomu viac povedať, ako to funguje alebo ako je to riešené? Vďaka.

**Comment by anton-pytel** [comment]
Ahoj, ak nie je prihlaseny, tak neukladame nic. Ak je prihlaseny, tak si ulozime session, tj nemusi sa stale prihlasovat.

![image](https://user-images.githubusercontent.com/15068798/147978418-8b665974-ec8e-41e6-a3f8-1229f85b385f.png)

Neviem ci pomohlo take vysvetlenie.

**Comment by MajkaPytlova** [comment]
Ahoj, preposlala som, tak uvidím :)

Majka

**Comment by anton-pytel** [comment]
Sak nech sa aj on prihlasi do github, nemusis preposielat ;)

**Comment by anton-pytel** [comment]
Pozeral som este tieto cookies a zbierame len nevyhnutne:

https://openli.com/guides/cookie-consent 

- takze mal by len stacit kratky textik, ze ich vyuzivame - niekde na stranku buchnut.  Vyuzivame ich na zabezpecenie moznosti bezpecne sa prihlasit.

**Comment by MajkaPytlova** [comment]
A mojou úlohou je napísať ten textík a rozmyslieť si, kam to šupneme, dobre som to pochopila alebo?

**Comment by anton-pytel** [comment]
ano :)
