### ISSUE TITLE
číslo účtu 

### ISSUE THREAD

**Issue by MajkaPytlova** [anton-pytel/camp-app#26]
Ešte sme sa bavili s Kikou a Vejkou, že  keby rodičia nechcú využiť ten QR kód, či by predsalen mohlo byť číslo účtu dostupné v účte rodiča. Vďaka.

**Comment by anton-pytel** [comment]
aktualne riesene takto 
![image](https://user-images.githubusercontent.com/15068798/159166465-87cfee74-78aa-4d8c-9888-8ff844eddd47.png)
(meno som dal trochu dost testovacie, ale snad sa da pochopit ako to teraz je.) keby nie tak kludne mozeme znovu otovorit toto issue.
