### ISSUE TITLE
GDPR súhlas do registrácie

### ISSUE THREAD

**Issue by MajkaPytlova** [anton-pytel/camp-app#28]
Ahoj Tonko, posielam znenie súhlasov GDPR, ktoré by mali byť na konci pri registrácii. Ďakujem :)

Súhlasím so spracovaním osobných údajov maloletého dieťaťa v zmysle 18/2018 Z. z. o ochrane osobných údajov a o zmene a doplnení niektorých zákonov za účelom vyhotovenia obrazových a obrazovo-zvukových záznamov z podujatia ako aj ich zverejnenia: 1. na webovom sídle www.farapd.sk a www.tabor.farapd.sk 2. na sociálnych sieťach  3. v tlačenom médiu (časopis Bartolomej) vydávanom farnosťou Prievidza-mesto. Zároveň ako dotknutá osoba potvrdzujem, že som sa oboznámila s princípmi ochrany osobných údajov Rímskokatolíckej cirkvi v Slovenskej republike.

Potvrdzujem, že som sa ako dotknutá osoba poučila o spracúvaní
mojich osobných údajov a osobných údajov môjho dieťaťa prevádzkovateľom ZKSM, Dolný
Šianec 1013/1, 911 01 Trenčín v súlade so zákonom č. 18/2018 Z. z. o ochrane osobných
údajov pre účely organizovania tábora. Viac informácii o spracúvaní a ochrane osobných
údajov: https://zksm.sk/pre-clenov/administrativa/#GDPR.

**Comment by anton-pytel** [comment]
pridal som znenia, takto to vyzera:

![image](https://user-images.githubusercontent.com/15068798/160211228-9353d302-fc24-4b95-b635-14748e054a44.png)

jedna otazka k tomuto: https://zksm.sk/pre-clenov/administrativa/#GDPR = tam sa pise, ze zbieraju len dátum narodenia, nie je tam rodne cislo, je to OK?

**Comment by MajkaPytlova** [comment]
Vďaka vyzerá to super. No to je dosť dobrá otázka. My sme to mali v jednej prihláške, ale ako tak pozerám, tak v druhej nemáme rodné číslo... už som písala Kike, že čo s tým. ;)

**Comment by anton-pytel** [comment]
aktualne je nasadena verzia s datumom. zatvaram
