### ISSUE TITLE
QR kód 

### ISSUE THREAD

**Issue by MajkaPytlova** [anton-pytel/camp-app#29]
Ešte taká vec, občas sa stane, že nezobrazí QR kód na platbu. Neviem, či ti zobrazilo tento obrázok, ale otvorila som akože ten nezobrazený QR kód na novej karte a toto mi vypísalo. 
![image](https://user-images.githubusercontent.com/95722179/149123316-d94b438f-1457-4e7a-9a6a-f935fb5b5829.png)

**Comment by anton-pytel** [comment]
aktualne neviem tuto chybu zreprodukovat, ked sa podari popisat presnejsi postup krokov, urcite sa na to pozriem,

**Comment by anton-pytel** [comment]
zatvram, ak by sa zopakovalo otvorime nanovo.
