### ISSUE TITLE
kalendár

### ISSUE THREAD

**Issue by MajkaPytlova** [anton-pytel/camp-app#30]
Bavili sme sa aj o tom, že by sme mohli na stránku dať kalendár s dátumami zaplatenia záloh, stretnutí rodičov a tábora a pod.

**Comment by anton-pytel** [comment]
Toto sa planuje robit do spustenia registracie? ak ano, tak nejake podklady by sa hodili. (na to sme nejak zabudli vcera)

**Comment by MajkaPytlova** [comment]
Toto nemusí byť do registrácie. Zatiaľ ani ja neviem, kde a ako to vymyslieť na tú stránku... skôr by som to možno riešila formou hromadných mailov alebo pridania oznamu do informácií, že sa blíži ten a ten termín. Neviem, ešte som si túto časť neusporiadala v hlave popravde, ale isto viem, že do registrácie to netreba. ;)

**Comment by anton-pytel** [comment]
Oki, preradzujem na teba, ked budes mat podklady daj vediet.

**Comment by anton-pytel** [comment]
len pre istotu tato uloha je duplicita s tymto #41 predpokladam, tj toto zatvaram.
