### ISSUE TITLE
Sprístupniť časti webu na upravovanie pre Majku :)

### ISSUE THREAD

**Issue by MajkaPytlova** [anton-pytel/camp-app#34]
Informácie o tábore - určite by som rada upravovala tie texty a zvýraznila, čo treba
Náš tím - pridávanie/odoberanie ľudí - fotiek + textov
Hymna - vloženie nového textu a prehranie hudby (+ pridanie starej do tej hornej lišty)
Sponzory - to sme skúšali

**Comment by anton-pytel** [comment]
Nie som si isty ako myslis pridanie starej hymny do hornej listy, vsetko ostatne je pripravene na dynamicke upravovanie v ramci tohto [commitu](https://github.com/anton-pytel/camp-app/pull/37/commits/b0849694e6a940f5113536e8af629fa4f785ad2a).

**Comment by MajkaPytlova** [comment]
No myslela som to tak, že táto hymna je z minulého roka zatiaľ. A keď sa urobí nová, tak by sa tá dala namiesto tejto, čo tam je a tá (stará) by sa nechala na stránke niekde neviem, kde, ale spomínal si, že by som si vedela doplniť do menu ďalší nejaký "prečinok", tam kde je Domov, Informácie, Prihlasovanie... tam, že by sa dala potom aj Hymna (ale vlastne to tam už asi je, že?) :D tak potom neviem... ale Štefan mal k tomu nejaký nápad tuším...

**Comment by anton-pytel** [comment]
Oki, dajte potom vediet, Za mna je vsetko co som vedel spravit hotovo. chyba uz len produkcne nasadenie a spisanie navodov.

**Comment by MajkaPytlova** [comment]
Ďakujeme. A teda oficiálna stránka je tabor.farapd.sk? Chcem urobiť ten qr kod na plagát :)

**Comment by anton-pytel** [comment]
Ano https://tabor.farapd.sk (pozor nie www.tabor.farapd.sk), ale tam to este nie je dokonfigurovane, [tu ](https://github.com/anton-pytel/camp-app/issues/38)je zoznam co este treba spravit, aby sme mali funkcnu produkciu. Su tam aj nejake veci, ktore neviem povedat, takze budem potrebovat informacie a aj termin, kedy mozem spustit stranku.

**Comment by MajkaPytlova** [comment]
Keď otváram tento link https://tabor.farapd.sk, tak to chce odo mňa prihlásenie, ale neviem, aké, lebo tie údaje, čo som mala mi nechce zobrať...

**Comment by anton-pytel** [comment]
ved ti pisem, ze

> ale tam to este nie je dokonfigurovane, https://github.com/anton-pytel/camp-app/issues/38 je zoznam co este treba spravit...

**Comment by MajkaPytlova** [comment]
Ahaaa, už chápem :D

**Comment by anton-pytel** [comment]
ak by bolo treba nejaku dokumentaciu doplnit, daj vediet, nateraz zatvaram.

**Comment by MajkaPytlova** [comment]
Dobre ;)

Dňa ut 29. 3. 2022, 23:24 Anton Pytel ***@***.***> napísal(a):
