### ISSUE TITLE
Konfiguracia produkcie

### ISSUE THREAD

**Issue by anton-pytel** [anton-pytel/camp-app#38]
- [x] init databazy - nastavit pristupy
- [x] vytvorit cms stranku home po slovensky
- [x] vytvorit registraciu (spolu s upravou s ENV premenou) + platby
- [x] Naplnit galeriu
- [x] naplnit animatorov
- [x] naloadovat video rucne
- [x] predvyplnit Vseobecne informacie 
- [x] naplnit sponzorov

**Comment by MajkaPytlova** [comment]
No čo sa týka videa, to ti viem poslať, ak s tým nepotrebuješ od Štefana niečo. Zazdieľam na mail, lebo tu sa mi nezmestí, lebo má 17 MB :D 
Animátori asi pôjdu aj priebežne nejako, že tých doplníme postupne
Sponzori sú zatiaľ všetci

A čo znamená predvyplniť Všeobecné info?

**Comment by anton-pytel** [comment]
- Vseobecne info ti este ukazem ako je to spravene (aby si si to mohla doplnat), je to kvoli tomu, ak nebudes nic menit, tak zatial nic netreba.
- Rovnako ti ukazem ako funguje galeria
- taktiez animatorov ako pridavat - pozor chybaju este kresbofotky
- chyba mi vyska platby a zalohovej platby
- sponzorov - karpis - treba doplnit rucne ked bude produkcia hotova

**Comment by MajkaPytlova** [comment]
Dobre a kedy by sme sa mohli dohodnúť, že by si mi to ukázal? Rozmýšľam, že teoreticky zajtra po práci by som vedela dobehnúť aj autom. :) Kresbičky sa robia, tie ti viem tiež aspoň pár preposlať a tie, ktoré nie sú, tam zatiaľ iba nechať biely priestor. 
Celková suma tábora je 130 eur a záloha je 60 eur.
