### ISSUE TITLE
kalendár alias odpočítavač

### ISSUE THREAD

**Issue by MajkaPytlova** [anton-pytel/camp-app#41]
Namiesto kalendára som dostala celkom dobrý tip, že by sme tam mohli dať odpočítavanie dní do tábora a ďalšie termíny by sme im potom pripomínali mailom. Čo na to povieš? Akože je to vec, ktorá tam za mňa nemusí byť do spustenia stránky, iba nápad, keď by bol čas.

**Comment by anton-pytel** [comment]
moze byt, tu je rovno aj riesenie , ktore mozem niekedy vyskusat,
https://stackoverflow.com/questions/10603409/how-to-implement-countdown-timer-in-django

 len skus nahodit, kde by to bolo, mne sa tam tie datumy hodili, ale toto moze byt tiez pekne.

**Comment by anton-pytel** [comment]
Ako s tymto kalendarom/count down casovacom?

**Comment by MajkaPytlova** [comment]
No, to by sme mohli spustiť dnes od polnoci, akože mesiac pred táborom, ak stíhaš, namiesto tej hymny, keď sa Peťo neozýva...  ja by som to hodila na tú prázdnu stránku, čo tam máme na konci, dalo by sa?

**Comment by anton-pytel** [comment]
Dnes to asi nestihnem, skusim cez vikend. Nemyslim, ze niekto teraz tu stranku pozera okrem tych co sa chcu prihlasit, zmenit, zaplatit. Najskor budu pozerat tyzden alebo 2 pred taborom, co treba zobrat. Ak to treba nevyhnutne dnes, daj vediet. (v odpocitavadle nebude vidiet od kedy ide - ci mesiac pred alebo 28 dni pred a pod, len kolko ostava do tabora :) )

**Comment by MajkaPytlova** [comment]
Veď pravda, akože popravde sa mi nechce už nič hrotiť s týmto táborom, čiže stačí to pokojne spustiť aj týždeň pred táborom, môžeme sa tak dohodnúť ;)

**Comment by anton-pytel** [comment]
nakoniec sa mi podarilo to pozriet. @MajkaPytlova pozri ako vyzera odpocitavadlo na https://test.farapd.sk/

nejaky text mozeme pridat alebo format upravit a potom prehodit do https://tabor.farapd.sk

**Comment by MajkaPytlova** [comment]
Jeeejo, super to je, ďakujem. Akože ku dokonalosti mám iba tri body:

> doplnila by som nad to text: "Vidíme sa o:" (dní minút sekúnd) vo veľkosti písma ako je nad tým v tlačidlách - Pozri video alebo Prihlás sa 
> celý rámik s časom by som dala zarovno obom tlačidlám
> detail, že tlačidlá sú na rohoch oválne, tak iba z estetického hľadiska by som dala aj ten rámik s časom taký
A ďakujem naozaj veľmi pekne. Je to super, nadšená som z toho riadne :)

**Comment by anton-pytel** [comment]
Skus pozriet teraz na https://test.farapd.sk/  a ak je ok a trufas si, mozes skusit prehodit to z testu na tabor.farapd.sk :), ked si netrufas a je to ok, daj vediet - prehodim.
