### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by MajkaPytlova** [anton-pytel/camp-app#43]
![image](https://user-images.githubusercontent.com/95722179/161118799-67c105ba-a635-43f3-9f62-6d9359e1598a.png)

**Comment by anton-pytel** [comment]
oprava nasadena a bol problem, ze si dala svoj email, lebo sa bil s tym druhym uctom, ale opravil som tak aby sa to nedialo (dvaja rodicia s rovnakym emailom nemozu byt)
