### ISSUE TITLE
údaje o animátoroch

### ISSUE THREAD

**Issue by MajkaPytlova** [anton-pytel/camp-app#46]
Pripájam zoznam, čo by si Kika predstavovala vedieť o animátoroch a následne mať aj v offline verzii (podobne ako deti)
- meno a priezvisko
- dátum narodenia
- adresa
- alergie/intolerancie
A ešte dve, čo si úplne neviem predstaviť, ako by sa dali urobiť:
- súhlas od rodiča, tí čo nemajú ešte 18, ale neviem, ako by sa to dalo vymyslieť 
- a tiež nejako možno zaškrtnúť, že súhlasia so zverejnením fotografií

**Comment by anton-pytel** [comment]
Zavolajme si k tomu ked budes mat cas, lebo chapem to viacerymi sposobmi, tak nech to spravim tym spravnym.

**Comment by anton-pytel** [comment]
Predbezne sme dohodli doplnit "flag" na (ne)zobrazenie na stranke. prve 3 su jednoduche a tie posledne 3 potrebujem dospecifikovat.

**Comment by MajkaPytlova** [comment]
takže tento rok platí verzia, že údaje o animátoroch doplníme my (prvé štyri body) a zvyšok (súhlas na fotenie a od rodičov) vypíšu rodičia na papier

**Comment by anton-pytel** [comment]
Je mozne pridavat informacie o animatoroch a exportovat.  vid https://github.com/anton-pytel/camp-app/wiki/Animators
