### ISSUE TITLE
úpravy na stránke

### ISSUE THREAD

**Issue by MajkaPytlova** [anton-pytel/camp-app#50]
Ešte ma Kika poprosila, či by sa nedala posunúť tá čiara dole v časti sponzorov pod ten text "Ďakujeme aj všetkým anonymným sponzorom", aby sa oddelila tá veta o cookies. Vďaka. Lebo toto asi neviem upraviť, ale som neprišla na to, ako.

**Comment by anton-pytel** [comment]
text som posunul dole, snad je to ok.
