### ISSUE TITLE
Animátori

### ISSUE THREAD

**Issue by MajkaPytlova** [anton-pytel/camp-app#54]
Pridala som niektoré práva Alžbete Blahovej, bude si vedieť pridať a odobrať info o "Animator diseases", a vidieť "Child group" a "Group Animator."
Ale neviem, či si vie doplniť aj "General" informácie. To by som ťa poprosila, aby si jej to sprístupnil alebo povedať mi, ktoré to je používateľské oprávnenie, doplním to. 
A potom popridávam tieto práva aj ostatným animátorom, nech si sami vyplnia informácie. Dám im k tomu aj call, že im môžem s tým pomôcť, ak by bolo pre nich veľmi náročné vyplniť údaje.

**Comment by anton-pytel** [comment]
Vytvoril som skupinu animator a pridelil vsetkym animatorom, ak by im nieco chybalo, daj vediet.
