### ISSUE TITLE
4. pripravit Payby Square 

### ISSUE THREAD

**Issue by anton-pytel** [anton-pytel/camp-app#9]
4. pripravit QR kod na zalohovu platbu + pripravit QR kod na doplnenie

**Comment by anton-pytel** [comment]
@MajkaPytlova prosim, zisti mi cislo uctu na ktore sa bude mat zalohova + doplnujuca platba posielat.

**Comment by MajkaPytlova** [comment]
To som ešte neposielala? :D no tu je, nech sa páči: SK31 8330 0000 0024 0188 0167
A teda do poznámky pri platbe dajú rodičia rodné číslo alebo meno a priezvisko dieťaťa?

**Comment by anton-pytel** [comment]
> To som ešte neposielala? :D no tu je, nech sa páči: SK31 8330 0000 0024 0188 0167 A teda do poznámky pri platbe dajú rodičia rodné číslo alebo meno a priezvisko dieťaťa?

to uz v QR kode pripravim ja, budu to moct po naskenovani upravit, ale nebude treba
